spring:
  datasource:
    hikari:
      poolName: Hikari
      auto-commit: 'false'
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: example